### ISSUE TITLE
Morpho Aave v3 subgraph

### ISSUE THREAD

**Issue by julien-devatom** [morpho-association/morpho-subgraphs#1]
```[tasklist]
### TODO
- [ ] add mapping for collateral supply/withdraw
- [x] Add new position type: collateral
- [ ] Deploy on hosted service
```
